- name: Set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  when:
    - ansible_hostname != inventory_hostname

- name: Set timezone
  become: true
  timezone:
    name: "{{ timezone }}"
  vars:
    timezone: "Europe/Amsterdam"

- name: Install Python3 interpreter
  become: true
  apt:
    name: python3
    state: present
    update_cache: true