- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when:
    - ansible_hostname != inventory_hostname

- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ timezone }}"
  vars:
    timezone: "Europe/Amsterdam"

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - python3
    - btop
    - ufw
