- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when:
    - ansible_hostname != inventory_hostname

- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ timezone }}"
  vars:
    timezone: "Europe/Amsterdam"

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - python3
    - btop
    - ufw

- name: Enable passwordless sudo for {{ ansible_user }}
  when: ansible_user != 'root'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ ansible_user }}
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: true
    validate: 'visudo -cf %s'
    mode: '0640'
