- name: Set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  when:
    - ansible_hostname != inventory_hostname

- name: Set timezone
  become: true
  timezone:
    name: "{{ timezone }}"
  vars:
    timezone: "Europe/Amsterdam"

- name: Install Python3 interpreter
  become: true
  apt:
    name: python3
    state: present
    update_cache: true

- name: Install btop
  become: true
  apt:
    name: btop
    state: present
    update_cache: true

- name: APT - Add Fastfetch PPA
  become: true
  apt_repository:
    repo: 'ppa:zhangsongcui3371/fastfetch'
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'

- name: APT - Install fastfetch
  become: true
  apt:
    name: 'fastfetch'
    state: present
    update_cache: true
