# Dependencies
- name: Install dependencies for Zsh
  become: true
  ansible.builtin.package:
    name:
      - 'curl'
      - 'git'
      - 'zsh'
    state: present

# Install Oh My Zsh
- name: APT - Install Zsh
  become: true
  ansible.builtin.package:
    name: 'zsh'
    state: present

- name: SHELL - Install Oh My Zsh
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  register: ohmyzsh_installed
  args:
    creates: ~/.oh-my-zsh

- name: Set ZSH_THEME in .zshrc
  become: true
  become_user: "{{ ansible_user }}"
  when: ohmyzsh_installed.rc == 0
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="agnoster"'
    state: present

- name: Set Zsh as default shell for user
  become: true
  when: ohmyzsh_installed.rc == 0
  ansible.builtin.command: usermod --shell /bin/zsh "{{ ansible_user }}"
  changed_when: false

# Install Zsh plugins (Zoxide)
- name: APT - Install dependencies for Zoxide
  become: true
  ansible.builtin.package:
    name: 'fzf'
    state: present

- name: SHELL - Install Zoxide for Zsh
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ajeetdsouza/zoxide/master/install.sh)"
  register: zoxide_check
  args:
    creates: ~/.local/bin/zoxide

- name: Add ~/.local/bin to PATH
  become: true
  become_user: "{{ ansible_user }}"
  when: zoxide_check.rc == 0
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present

- name: Add Zoxide to .zshrc
  become: true
  become_user: "{{ ansible_user }}"
  when: zoxide_check.rc == 0
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'eval "$(zoxide init zsh)"'
    state: present

# Fix `zsh | (anon):12: character not in range` issue with zsh
# https://gist.github.com/jadia/1f4c2190730ef646d41823b6a6c30926
#
# Also issues with btop on some LXCs
# "ERROR: No UTF-8 locale detected!"
- name: Add correct language pack
  become: true
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.package:
    name: 'language-pack-en'
    state: present

- name: Update locale
  become: true
  ansible.builtin.command: update-locale
  changed_when: false

- name: Set locale to en_US.UTF-8
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: 'LANG=en_US.UTF-8'
    state: present
  with_items:
    - /etc/default/locale
    - /etc/locale.conf

- name: Enable en_US.UTF-8 UTF-8 locale
  become: true
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: '^# en_US.UTF-8 UTF-8'
    line: 'en_US.UTF-8 UTF-8'
    state: present

- name: Generate locale
  become: true
  ansible.builtin.command: locale-gen
  changed_when: false
