- name: Proxmox setup
  hosts:
    - hypervisors
  roles:
    - { role: apt, tags: apt }
    - { role: proxmox, tags: proxmox }
    - { role: ssh, tags: ssh }
  handlers:
    - name: Restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
