# Setup Proxmox hypervisors: SSH, HA, Keepalived and Cloudflared
# Usage: ansible-playbook setup_hypervisors.yml -J
- name: Proxmox setup
  hosts:
    - hypervisors
  roles:
    - { role: apt, tags: apt }
    - { role: proxmox, tags: proxmox }
    - { role: ssh, tags: ssh }
    - { role: monitoring, tags: monitoring }
  handlers:
    - name: Restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
    - name: Restart glances
      ansible.builtin.service:
        name: glances
        state: restarted
