- name: APT setup
  ansible.builtin.import_tasks: upgrade.yml

- name: Check vars
  ansible.builtin.debug:
    msg: "{{ apt_unattended_upgrades }}"

- name: Unattended upgrades
  ansible.builtin.import_tasks: unattended-upgrades.yml
  when: apt_unattended_upgrades
