- name: Update packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 3600
    autoremove: true
  environment:
    DEBIAN_FRONTEND: noninteractive
