- name: Set DEBIAN_FRONTEND to noninteractive
  shell: export DEBIAN_FRONTEND=noninteractive
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Update packages
  become: true
  apt:
    upgrade: true