- name: NEW - Install traefik
  hosts: demo

  tasks:
    - name: Check if docker is installed
      stat:
        path: /usr/bin/docker
      register: docker_installed

    - name: Make sure the Traefik directory exists
      file:
        path: ~/docker/traefik/data
        state: directory
        mode: '0755'
      when: docker_installed.stat.exists == True

    - name: Copy docker compose file j2 template
      template:
        src: "./files/docker-compose.yml.j2"
        dest: ~/docker/traefik/docker-compose.yml
        owner: jordy
        group: jordy
        mode: 0644
      when: docker_installed.stat.exists == True

    - name: Copy traefik configuration file
      template:
        src: "./files/traefik.yml.j2"
        dest: ~/docker/traefik/data/traefik.yml
        owner: jordy
        group: jordy
        mode: 0644
      when: docker_installed.stat.exists == True

    - name: User input for Cloudflare token
      pause:
        prompt: "Enter your Cloudflare API token: "
      register: cf_token
      when: docker_installed.stat.exists == True

    - name: Create .env file
      copy:
        content: |
          CF_DNS_API_TOKEN={{ cf_token.user_input }}
        dest: ~/docker/traefik/.env
        owner: jordy
        group: jordy
        mode: 0644
      when: docker_installed.stat.exists == True

    - name: Make sure proxy docker network exists
      command: docker network create proxy
      when: docker_installed.stat.exists == True

    - name: Start the compose stack
      command: docker compose up -d
      args:
        chdir: ~/docker/traefik
      when: docker_installed.stat.exists == True

    


      