hypervisors:
  hosts:
    lab-pve-01:
      ansible_host: 10.0.0.101
    lab-pve-02:
      ansible_host: 10.0.0.102
  vars:
    ansible_user: root

vps:
  hosts:
    lab-vps-01:
      ansible_host: 10.0.10.101
    lab-vps-02:
      ansible_host: 10.0.10.102
    lab-vps-03:
      ansible_host: 10.0.10.103
    str-vps-01:
      ansible_host: 172.16.2.2
  vars:
    ansible_user: jordy

lxc:
  hosts:
    lab-dns-02:
    lab-mon-01:
    lab-proxy-01:
      ansible_host: 10.0.20.201
  vars:
    ansible_user: root

raspberry:
  hosts:
    lab-rpi-01:
      ansible_host: 10.0.10.21
    lab-rpi-02:
      ansible_host: 10.0.10.22
  vars:
    ansible_user: jordy
