proxmox:
  hosts:
    lab-pve-01:
      ansible_host: 100.72.155.135
    lab-pve-02:
      ansible_host: 100.96.34.25

virtual:
  hosts:
    lab-vps-01:
      ansible_host: 10.0.10.101
      ansible_user: jordy
    lab-vps-02:
      ansible_host: 10.0.10.102
      ansible_user: jordy
    lab-vps-03:
      ansible_host: 10.0.10.103
      ansible_user: jordy
    orc-vps-01:
      ansible_host: 100.102.124.47
      ansible_user: jordy

raspberry:
  hosts:
    lab-rpi-01:
      ansible_host: 10.0.10.21
      ansible_user: jordy
    lab-rpi-02:
      ansible_host: 10.0.10.22
      ansible_user: jordy

demo:
  hosts:
    demo-vps-01:
      ansible_host: 100.116.247.86
      ansible_user: jordy
    demo-vps-02:
      ansible_host: 100.94.38.56
      ansible_user: jordy
