homeservers:
  hosts:
    lab-vps-01:
      ansible_host: 100.123.120.33
      ansible_user: jordy
    lab-vps-02:
      ansible_host: 100.114.244.139
      ansible_user: jordy
    lab-vps-03:
      ansible_host: 100.98.101.15
      ansible_user: jordy

raspberry:
  hosts:
    lab-rpi-01:
      ansible_host: 100.75.114.157
      ansible_user: jordy

oracleservers:
  hosts:
    orc-vps-01:
      ansible_host: 100.102.124.47
      ansible_user: jordy

virtualservers:
  children:
    homeservers:
    oracleservers:

demo:
  hosts:
    demo-vps-01:
      ansible_host: 100.116.247.86
      ansible_user: jordy




hypervisors:
  hosts:
    lab-pve-01:
      ansible_host: 100.72.155.135
      ansible_user: root
    lab-pve-02:
      ansible_host: 100.96.34.25
      ansible_user: root