hypervisors:
  hosts:
    lab-pve-01:
      ansible_host: 10.0.0.101
    lab-pve-02:
      ansible_host: 10.0.0.102
  vars:
    ansible_user: root

vps:
  hosts:
    lab-vps-01:
      ansible_host: 10.0.10.101
    lab-vps-02:
      ansible_host: 10.0.10.102
    lab-vps-03:
      ansible_host: 10.0.10.103
    lab-pbs-01:
      ansible_user: root
      ansible_host: 10.0.10.150
    str-vps-01:
      ansible_host: 172.16.2.2
    orc-vps-01:
      ansible_host: 172.16.2.3
  vars:
    ansible_user: jordy

lxc:
  hosts:
    lab-dns-01:
    lab-mon-01:
    lab-aut-01:
  vars:
    ansible_user: root

raspberry:
  hosts:
    lab-rpi-01:
      ansible_host: 10.0.10.21
    lab-rpi-02:
      ansible_host: 10.0.10.22
  vars:
    ansible_user: jordy
