hypervisors:
  hosts:
    lab-pve-01:
      ansible_host: 10.0.0.101
    lab-pve-02:
      ansible_host: 10.0.0.102
  vars:
    ansible_user: root
    keepalived_virtual_ip: 10.0.0.100
    keepalived_virtual_ip_cidr: 24

virtualmachines:
  hosts:
    lab-vps-01:
      ansible_host: 10.0.10.101
    lab-vps-02:
      ansible_host: 10.0.10.102
    lab-vps-03:
      ansible_host: 10.0.10.103
    str-vps-01:
      ansible_host: 172.16.2.2
  vars:
    ansible_user: jordy

raspberry:
  hosts:
    lab-rpi-01:
      ansible_host: 10.0.10.21
    lab-rpi-02:
      ansible_host: 10.0.10.22
  vars:
    ansible_user: jordy