servers:
  hosts:
    lab-vps-01:
      ansible_host: 192.168.2.33
      ansible_user: jordy
    lab-vps-02:
      ansible_host: 192.168.2.3
      ansible_user: jordy
    lab-vps-03:
      ansible_host: 192.168.2.143
      ansible_user: jordy

hypervisors:
  hosts:
    lab-pve-01:
      ansible_host: 192.168.2.88
      ansible_user: root
    lab-pve-02:
      ansible_host: 192.168.2.89
      ansible_user: root