---
- name: Check if cloudflared is installed
  ansible.builtin.shell: |
    set -o pipefail
    dpkg -l | grep -q cloudflared
  register: cloudflared_installed
  failed_when: false
  changed_when: false

- name: Add Cloudflare GPG key
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Download Cloudflare GPG key
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /usr/share/keyrings/cloudflare-main.gpg
    mode: '0644'
  when: cloudflared_installed.rc != 0

- name: Add Cloudflare repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared {{ ansible_facts['distribution_release'] }} main"
    filename: 'cloudflared'
  when: cloudflared_installed.rc != 0 and (ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu')

- name: Install cloudflared
  ansible.builtin.apt:
    name: cloudflared
    state: present
    update_cache: true
  when: cloudflared_installed.rc != 0

- name: Check if cloudflared service is installed
  ansible.builtin.systemd:
    name: cloudflared.service
    state: started
  failed_when: false

- name: Install cloudflared service
  ansible.builtin.command: cloudflared service install {{ cloudflared_token }}
  args:
    creates: /etc/systemd/system/cloudflared.service
