- name: Ensure Glances dependencies are installed
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3
      - python3-fastapi
    state: present
    update_cache: true

- name: Install Glances using pip
  ansible.builtin.pip:
    name: glances
    state: present
    executable: pip3
    extra_args: --break-system-packages

- name: Create systemd service for Glances
  ansible.builtin.template:
    src: ./templates/glances.service.j2
    dest: /etc/systemd/system/glances.service
    mode: "0644"
  notify: Restart glances

- name: Start and enable Glances service
  ansible.builtin.systemd:
    name: glances
    enabled: true
    state: started
    daemon_reload: true
