- name: Install docker package with pip3
  become: true
  pip:
    name: docker
    executable: pip3
    break_system_packages: true

- name: Add docker_mk.py to CheckMK plugins (wget from https://checkmk.hoebergen.net/cmk/check_mk/agents/plugins/mk_docker.py)
  become: true
  get_url:
    url: https://checkmk.hoebergen.net/cmk/check_mk/agents/plugins/mk_docker.py
    dest: /usr/lib/check_mk_agent/plugins/mk_docker.py
    mode: '0754'
    owner: root
    group: root
    force: yes
  
- name: Configure Docker monitoring
  become: true
  get_url:
    url: https://checkmk.hoebergen.net/cmk/check_mk/agents/cfg_examples/docker.cfg
    dest: /etc/check_mk/docker.cfg
    mode: '0644'
    owner: root
    group: root
    force: yes

- name: Monitor on container name instead of ID
  become: true
  lineinfile:
    path: /etc/check_mk/docker.cfg
    regexp: '^skip_sections:.*'
    line: '# skip_sections: docker_node_disk_usage,docker_node_images'
    state: present