- name: Include checkmk variables
  ansible.builtin.include_vars:
    file: vars/checkmk.yml

- name: Include CheckMK agent role
  ansible.builtin.include_role:
    name: checkmk.general.agent

- name: Install docker package with pip3
  become: true
  ansible.builtin.pip:
    name: docker
    executable: pip3
    break_system_packages: true
  when: checkmk_docker != "disabled"

- name: Add docker_mk.py to CheckMK plugins
  become: true
  ansible.builtin.get_url:
    url: "{{ checkmk_agent_server_protocol }}://{{ checkmk_agent_server }}/{{ checkmk_agent_site }}/check_mk/agents/plugins/mk_docker.py"
    dest: /usr/lib/check_mk_agent/plugins/mk_docker.py
    mode: '0754'
    owner: root
    group: root
    force: true
  when: checkmk_docker != "disabled"

- name: Configure Docker monitoring
  become: true
  ansible.builtin.get_url:
    url: "{{ checkmk_agent_server_protocol }}://{{ checkmk_agent_server }}/{{ checkmk_agent_site }}/check_mk/agents/cfg_examples/docker.cfg"
    dest: /etc/check_mk/docker.cfg
    mode: '0644'
    owner: root
    group: root
    force: true
  when: checkmk_docker != "disabled"

- name: Disable unused sections
  become: true
  ansible.builtin.lineinfile:
    path: /etc/check_mk/docker.cfg
    regexp: '^skip_sections:.*'
    line: 'skip_sections: docker_container_diskstat'
    state: present
  when: checkmk_docker != "disabled"
