- name: Retrieve variables
  ansible.builtin.include_vars: vars/zabbix.yml

- name: Remove old Agent
  become: true
  block:
    - name: Remove old Zabbix repository package
      ansible.builtin.apt:
        name: zabbix-agent
        state: absent

    - name: Remove old Zabbix Agent configuration
      ansible.builtin.file:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent

- name: Download Zabbix repository
  ansible.builtin.get_url:
    url: "{{ zabbix_agent_ubuntu_2404_url }}"
    dest: "/tmp/{{ zabbix_agent_ubuntu_2404_file }}"
    mode: "0644"

- name: Install Zabbix repository package
  ansible.builtin.apt:
    deb: "/tmp/{{ zabbix_agent_ubuntu_2404_file }}"

- name: Install Zabbix Agent 2 package
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - zabbix-agent2
    state: present

- name: Update Zabbix Agent 2 configuration
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: "^{{ item.key }}=.*"
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - { key: "Server", value: "{{ zabbix_server_ip }}" }
    - { key: "ServerActive", value: "{{ zabbix_server_ip }}" }
    - { key: "Hostname", value: "{{ ansible_hostname }}" }

- name: Restart Zabbix Agent 2 service
  become: true
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
    enabled: true
