- name: Initial setup for servers
  hosts: demo
  become: true

  tasks:
  ## Initial setup
    - name: Update packages
      package:
        name: '*'
        state: latest

  ## Install Oh My Zsh
    - name: Install dependencies for Oh My Zsh
      become: true
      package:
        name: 'zsh'
        state: present

    - name: Check if Oh My Zsh is installed (1/2)
      stat:
        path: ~/.oh-my-zsh
      register: ohmyzsh_installed

    - name: Install Oh My Zsh
      become_user: "{{ ansible_user }}"
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: ohmyzsh_installed.stat.exists == False

    - name: Check if Oh My Zsh is installed (2/2)
      stat:
        path: ~/.oh-my-zsh
      when: ohmyzsh_installed.stat.exists == False
      register: ohmyzsh_installed

    - name: Set Zsh as default shell for user
      become_user: root
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh

  ## Install Zsh plugins (Zoxide)
    - name: Install Zoxide for Zsh
      become_user: "{{ ansible_user }}"
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ajeetdsouza/zoxide/master/install.sh)"

    - name: Add ~/.local/bin to PATH
      become_user: "{{ ansible_user }}"
      lineinfile:
        path: ~/.zshrc
        line: 'export PATH="$HOME/.local/bin:$PATH"'
        state: present

    - name: Add Zoxide to .zshrc
      become_user: "{{ ansible_user }}"
      lineinfile:
        path: ~/.zshrc
        line: 'eval "$(zoxide init zsh)"'
        state: present

    ## Add aliases to .zshrc
    - name: Add docker aliases to .zshrc
      become_user: "{{ ansible_user }}"
      lineinfile:
        path: ~/.zshrc
        line: 'alias d="docker"'
        state: present

    - name: Add docker compose aliases to .zshrc
      become_user: "{{ ansible_user }}"
      lineinfile:
        path: ~/.zshrc
        line: 'alias dc="docker compose"'
        state: present
