- name: SERVERS - Update all packages
  hosts: virtualservers, raspberry, demo
  become: true

  tasks:
    - name: Set DEBIAN_FRONTEND to noninteractive
      shell: export DEBIAN_FRONTEND=noninteractive
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Update packages
      apt:
        update_cache: true
        upgrade: true
        autoremove: true
        autoclean: true