- name: SERVERS - Update all packages
  hosts: servers, demo
  become: true

  tasks:
    - name: Set DEBIAN_FRONTEND to noninteractive
      shell: export DEBIAN_FRONTEND=noninteractive
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Update packages
      apt:
        upgrade: true