- name: SERVERS - Update all packages
  hosts: virtualservers, raspberry, demo
  become: true

  tasks:
    - name: Set DEBIAN_FRONTEND to noninteractive
      shell: export DEBIAN_FRONTEND=noninteractive
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Disable upgrade of Tailscale
      dpkg_selections:
        name: tailscale
        selection: hold

    - name: Update packages
      apt:
        name: "*"
        force_apt_get: true
        state: latest
