# Setup Virtual Machines: SSH, Shell, Docker, Monitoring etc..
# Usage: ansible-playbook ./playbooks/setup_vps.yml -J
- name: VPS setup
  hosts:
    - vps
  roles:
    - { role: basics, tags: basics }
    - { role: ssh, tags: ssh }
    - { role: apt, tags: apt }
    - { role: shell, tags: shell }
    - { role: docker, tags: docker }
    - { role: motd, tags: motd }
    - { role: monitoring, tags: monitoring }

- name: LXC setup
  hosts:
    - lxc
  roles:
    - { role: basics, tags: basics }
    - { role: ssh, tags: ssh }
    - { role: apt, tags: apt }
    - { role: shell, tags: shell }
    - { role: motd, tags: motd }
    - { role: monitoring, tags: monitoring }
