# Setup Proxmox hypervisors: SSH, HA, Keepalived and Cloudflared
# Usage: ansible-playbook ./playbooks/setup_hypervisors.yml -J
- name: Proxmox setup
  hosts:
    - hypervisors
  roles:
    - { role: apt, tags: apt }
    - { role: proxmox, tags: proxmox }
    - { role: ssh, tags: ssh }
    - { role: monitoring, tags: monitoring }
